quarkus.http.port=8083

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=food
quarkus.datasource.password=food
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5443/orderdb

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

#REST clients vers autres microservices
quarkus.rest-client.customer-api.url=http://localhost:8081
quarkus.rest-client.restaurant-api.url=http://localhost:8082
quarkus.rest-client.delivery-api.url=http://localhost:8084