quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=food
quarkus.datasource.password=food
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5442/restaurantdb

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true